package com.reddefrijoles.pruebapokefeet

data class Pokemon(
    val id: Int,
    val nombre: String,
    val imagenColor: Int,
    val imagenBlack: Int,
    val categoria: String,
    val tipo1: String,
    val tipo2: String,
    val imagenTipo1: Int,
    val imagenTipo2: Int,
    val altura: String,
    val peso: String,
    val descripcion: String,
    val debilidad1: String = "None",
    val imagenDebilidad1: Int = 0,
    val debilidad2: String = "None",
    val imagenDebilidad2: Int = 0,
    val debilidad3: String = "None",
    val imagenDebilidad3: Int = 0,
    val debilidad4: String = "None",
    val imagenDebilidad4: Int = 0,
    val debilidad5: String = "None",
    val imagenDebilidad5: Int = 0,
    val debilidad6: String = "None",
    val imagenDebilidad6: Int = 0,
    val debilidad7: String = "None",
    val imagenDebilidad7: Int = 0,
)
